#!/usr/bin/env python3
"""Generate the showcase's board gallery from the boards repo.

    gallery.py [--boards-root DIR] [--pictures] [--check]

Reads gallery.yaml (the curated order, words and extra pictures), the boards
repo's register.yaml, and each board's own .kicad_pcb and state.json, and
writes two copies of the same gallery:

  gallery.tex      \\input by hwde-showcase.tex: "The boards" chapter
  ../../README.md  the part between the gallery:start and gallery:end markers

A board the register lists and gallery.yaml does not is still shown, in a
"New boards" section, with a blurb from its requirements.md ("## 1. Function")
or, when it has none, its register title. A board that never reached a routed
layout (phase below P7 and no fab package) is named in one line, not pictured.

--pictures first makes the picture of any shown board that has none in
renders/: from the board's own render in its workspace when it has one,
finished by _finish.py, else by render_boards.sh. --check writes nothing and
exits 1 when either copy would change.

JSON to stdout; exit 0 done (or up to date with --check), 1 out of date
(--check) or a board that should be pictured has no picture, 2 error.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import os
import re
import subprocess
import sys
import textwrap
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
README = REPO / "README.md"
TEX_OUT = HERE / "gallery.tex"
SPEC = HERE / "gallery.yaml"
RENDERS = HERE / "renders"
START = ("<!-- gallery:start - generated by docs/showcase/gallery.py from "
         "gallery.yaml and the boards repo; edit those, not this -->")
END = "<!-- gallery:end -->"

sys.path.insert(0, str(REPO / ".claude" / "skills" / "hwde" / "scripts"))
from lib import boardreg, env  # noqa: E402

PHASE_WORD = {0: "intake", 1: "research", 2: "architecture", 3: "parts",
              4: "schematic", 5: "board setup", 6: "placement", 7: "routing",
              8: "verification", 9: "manufacturability", 10: "ordering"}
ROUTED = 7          # a board at or past P7 has a routed layout to show
NUMBER = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight",
          "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen",
          "sixteen", "seventeen", "eighteen", "nineteen", "twenty",
          "twenty-one", "twenty-two", "twenty-three", "twenty-four",
          "twenty-five", "twenty-six", "twenty-seven", "twenty-eight",
          "twenty-nine", "thirty"]


def number(n: int) -> str:
    return NUMBER[n] if n < len(NUMBER) else str(n)


def phase_num(p) -> int:
    m = re.match(r"P(\d+)", str(p or ""))
    return int(m.group(1)) if m else -1


# ---------------------------------------------------------------- board facts
def _num(s: str) -> float:
    return float(s)


def pcb_facts(pcb: Path) -> dict:
    """Copper layers, outline bounding box (mm) and footprint count of a
    .kicad_pcb, read from the file's text (no KiCad needed)."""
    text = pcb.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"\n\t\(layers\b(.*?)\n\t\)", text, re.S)
    layers = len(re.findall(r'\(\d+ "[^"]*\.Cu" (?:signal|power|mixed|jumper)',
                            m.group(1))) if m else 0
    footprints = len(re.findall(r'\n\t\(footprint "', text))
    xs: list[float] = []
    ys: list[float] = []
    for item in text.split("\n\t(")[1:]:
        if not item.startswith("gr_") or '(layer "Edge.Cuts")' not in item:
            continue
        kind = item.split(None, 1)[0]
        pt = {k: (_num(a), _num(b)) for k, a, b in re.findall(
            r"\((start|end|mid|center) (-?[\d.]+) (-?[\d.]+)", item)}
        pts = [(_num(a), _num(b)) for a, b in
               re.findall(r"\(xy (-?[\d.]+) (-?[\d.]+)\)", item)]
        if kind == "gr_circle" and "center" in pt and "end" in pt:
            (cx, cy), (ex, ey) = pt["center"], pt["end"]
            r = math.hypot(ex - cx, ey - cy)
            pts += [(cx - r, cy - r), (cx + r, cy + r)]
        elif kind == "gr_arc" and {"start", "mid", "end"} <= set(pt):
            pts += _arc_extent(pt["start"], pt["mid"], pt["end"])
        else:
            pts += [pt[k] for k in ("start", "end") if k in pt]
        xs += [p[0] for p in pts]
        ys += [p[1] for p in pts]
    w = _tenth(max(xs) - min(xs)) if xs else 0.0
    h = _tenth(max(ys) - min(ys)) if ys else 0.0
    return {"layers": layers, "w": w, "h": h, "footprints": footprints}


def _tenth(v: float) -> float:
    """v to 0.1 mm, halves rounded up (53.55 prints as 53.6)."""
    return math.floor(v * 10 + 0.5 + 1e-6) / 10


def _arc_extent(s, m, e) -> list:
    """The end points of an arc and every axis extreme it sweeps through."""
    (ax, ay), (bx, by), (cx, cy) = s, m, e
    d = 2 * (ax * (by - cy) + bx * (cy - ay) + cx * (ay - by))
    if abs(d) < 1e-12:
        return [s, m, e]
    ux = ((ax * ax + ay * ay) * (by - cy) + (bx * bx + by * by) * (cy - ay)
          + (cx * cx + cy * cy) * (ay - by)) / d
    uy = ((ax * ax + ay * ay) * (cx - bx) + (bx * bx + by * by) * (ax - cx)
          + (cx * cx + cy * cy) * (bx - ax)) / d
    r = math.hypot(ax - ux, ay - uy)
    ang = [math.atan2(p[1] - uy, p[0] - ux) for p in (s, m, e)]

    def ccw(a, b):              # sweep from a to b counter-clockwise
        return (b - a) % (2 * math.pi)
    span = ccw(ang[0], ang[2])
    forward = ccw(ang[0], ang[1]) <= span     # mid lies on the ccw sweep
    out = [s, m, e]
    for k in range(4):
        t = k * math.pi / 2
        inside = (ccw(ang[0], t) <= span) if forward else \
            (ccw(ang[2], t) <= (2 * math.pi - span))
        if inside:
            out.append((ux + r * math.cos(t), uy + r * math.sin(t)))
    return out


def stage(ws: Path, state: dict) -> str:
    """Where the board stopped, in the words the gallery prints."""
    fab = ws / "fab"
    if (fab / "tracking.json").exists():
        return "ordered and made"
    failing = [phase_num(g.get("phase")) for g in (state.get("gates") or {}).values()
               if isinstance(g, dict) and g.get("status") == "fail"]
    if failing:
        p = min(failing) if min(failing) >= 0 else phase_num(state.get("phase"))
        return f"{PHASE_WORD.get(p, 'checks')}, findings open"
    if has_package(ws):
        return "package ready"
    return f"stopped at {PHASE_WORD.get(phase_num(state.get('phase')), 'intake')}"


def has_package(ws: Path) -> bool:
    fab = ws / "fab"
    return fab.is_dir() and any(fab.glob("*gerbers.zip")) and \
        any(f for f in fab.iterdir() if "CPL" in f.name or f.name.endswith("-pos.csv"))


def requirements_blurb(ws: Path) -> str | None:
    """The first plain paragraph of the board's "## 1. Function", cut to at
    most three sentences; None when there is none."""
    req = ws / "requirements.md"
    if not req.is_file():
        return None
    text = req.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"^##\s*1\.?\s*Function\s*$(.*?)(?=^##\s|\Z)", text, re.M | re.S)
    if not m:
        return None
    for para in re.split(r"\n\s*\n", m.group(1)):
        para = re.sub(r"[`*]", "", " ".join(para.split()))
        if not para or para.startswith(("-", "|", "#", ">")):
            continue
        # Drop the run's own bookkeeping (mode token, scope, binding limits).
        sentences = [s for s in re.split(r"(?<=[.!?])\s+(?=[A-Z])", para)
                     if not re.search(r"\bmode\b|^Scope\b|^Binding\b|^Stage under"
                                      r"|^Source\b|\bbrief carries\b", s, re.I)]
        out = ""
        for s in sentences[:3]:
            if out and len(out) + len(s) > 320:
                break
            out = f"{out} {s}".strip()
        if out:
            return out
    return None


def git_date(root: Path, rel: str) -> str | None:
    try:
        r = subprocess.run(["git", "-C", str(root), "log", "-1", "--format=%cs",
                            "--", rel], capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.TimeoutExpired):
        return None
    return r.stdout.strip() or None


def boards(root: Path) -> dict:
    """{name: board record} for every revision the register lists."""
    out = {}
    for pn, r in sorted(boardreg.load(root).items()):
        ws = root / r["dir"]
        _, name = boardreg.split_dir(r["dir"])
        rec = {"pn": pn, "dir": r["dir"], "name": name, "title": r.get("title") or name,
               "date": str(r.get("date") or ""), "ws": ws, "present": ws.is_dir()}
        state = {}
        try:
            state = json.loads((ws / "state.json").read_text(encoding="utf-8"))
        except (OSError, ValueError):
            pass
        rec["stage"] = stage(ws, state) if rec["present"] else "missing"
        rec["routed"] = rec["present"] and (
            phase_num(state.get("phase")) >= ROUTED or has_package(ws))
        pcb = ws / "kicad" / f"{r['dir']}.kicad_pcb"
        rec["facts"] = pcb_facts(pcb) if pcb.is_file() else None
        if rec["facts"] is None:
            rec["routed"] = False
        rec["changed"] = git_date(root, r["dir"]) or rec["date"]
        out[name] = rec
    return out


def finished(root: Path) -> list[str]:
    """Names of the boards the showcase must picture: every register entry
    with a routed layout."""
    return [n for n, b in boards(root).items() if b["routed"]]


# ---------------------------------------------------------------- the model
def model(root: Path, spec: dict) -> dict:
    allb = boards(root)
    words = spec.get("boards") or {}
    shown_in_spec: list[str] = []

    def plate(item):
        if isinstance(item, dict) and "view" in item:
            v = item["view"]
            return {"kind": "view", "image": v["image"], "name": v["name"],
                    "facts": v.get("facts", ""), "status": "",
                    "caption": " ".join(str(v.get("caption", "")).split())}
        name = item
        b = allb.get(name)
        if b is None or not b["routed"]:
            return None
        shown_in_spec.append(name)
        w = words.get(name) or {}
        blurb = w.get("blurb") or requirements_blurb(b["ws"]) or \
            f"{b['title'][0].upper()}{b['title'][1:]}."
        f = b["facts"]
        return {"kind": "board", "image": name, "name": name,
                "facts": f"{f['layers']} layers · {fmt(f['w'])} × {fmt(f['h'])} mm"
                         f" · {f['footprints']} footprints",
                "status": b["stage"], "caption": " ".join(str(blurb).split())}

    sections = []
    for sec in spec.get("sections") or []:
        blocks = []
        for blk in sec.get("blocks") or []:
            if "text" in blk:
                blocks.append({"kind": "text", "text": " ".join(blk["text"].split())})
            elif "newpage" in blk:
                blocks.append({"kind": "newpage"})
            elif "board" in blk or "view" in blk:
                p = plate(blk["board"] if "board" in blk else blk)
                if p:
                    blocks.append({"kind": "single", "plates": [p],
                                   "height": blk.get("height")})
            elif "pair" in blk:
                ps = [p for p in (plate(i) for i in blk["pair"]) if p]
                if ps:
                    blocks.append({"kind": "pair", "plates": ps})
        if any(b["kind"] in ("single", "pair") for b in blocks):
            sections.append({"title": sec["title"], "label": sec.get("label"),
                             "blocks": blocks,
                             "boards": [p["name"] for b in blocks
                                        for p in b.get("plates", []) if p["kind"] == "board"]})

    hero = spec.get("hero")
    placed = set(shown_in_spec) | ({hero} if hero else set())
    new = sorted((n for n, b in allb.items() if b["routed"] and n not in placed),
                 key=lambda n: (allb[n]["date"], allb[n]["pn"]), reverse=True)
    if new:
        plates = [plate(n) for n in new]
        blocks = [{"kind": "text", "text": (
            "These boards were added after the rest of this chapter was "
            "written, so each description is taken from the board's own "
            "requirements.")}]
        for i in range(0, len(plates), 2):
            blocks.append({"kind": "pair", "plates": plates[i:i + 2]})
        sections.insert(0, {"title": "New boards", "label": None,
                             "blocks": blocks, "boards": new})

    routed = [n for n, b in allb.items() if b["routed"]]
    order = sorted(routed, key=lambda n: (allb[n]["stage"] != "ordered and made",
                                          _neg_date(allb[n]["date"]), allb[n]["pn"]))
    table = []
    for n in order:
        b, f = allb[n], allb[n]["facts"]
        table.append({"name": n, "what": (words.get(n) or {}).get("what") or b["title"],
                      "layers": f["layers"], "size": f"{fmt(f['w'])} × {fmt(f['h'])}",
                      "stage": b["stage"]})
    unrouted = [b for b in allb.values() if b["present"] and not b["routed"]]
    return {"count": len(routed), "lead": " ".join(str(spec.get("lead", "")).split()),
            "ordered": sum(1 for b in allb.values() if b["stage"] == "ordered and made"),
            "table": table, "sections": sections, "unrouted": unrouted,
            "shown": sorted(placed | set(new)), "new": new,
            "changed": max((allb[n]["changed"] for n in routed), default="")}


def _neg_date(d: str) -> str:
    return "".join(chr(0x7f - ord(c)) for c in d)     # sorts newest first


def fmt(v: float) -> str:
    return f"{v:.1f}".rstrip("0").rstrip(".")


def long_date(iso: str) -> str:
    try:
        d = dt.date.fromisoformat(iso)
    except ValueError:
        return iso
    return f"{d.day} {d.strftime('%B %Y')}"


# ---------------------------------------------------------------- prose
def table_note(m: dict) -> list[str]:
    o = m["ordered"]
    ordered = (f"{number(o).capitalize()} board{'s were' if o != 1 else ' was'} "
               f"ordered and made, and {'their' if o != 1 else 'its'} files record "
               f"the JLCPCB order numbers.") if o else ""
    return [s for s in (
        "\u201cWhere it stopped\u201d is the last stage the board reached, and it "
        "does not mean the board is fit to release.", ordered,
        "\u201cPackage ready\u201d means every recorded check passed and the "
        "manufacturing package is built. \u201cFindings open\u201d means a check "
        "failed and a person has yet to rule on it. Each size is the bounding "
        "box of the board outline, and not every outline is a rectangle.") if s]


def unrouted_line(m: dict) -> str | None:
    u = m["unrouted"]
    if not u:
        return None
    names = [f"{b['name']} ({b['title']})" for b in u]
    listed = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
    if len(u) == 1:
        return (f"One more board stopped before layout and has no PCB to show: "
                f"{listed}. It is in the boards repository at the stage it reached.")
    return (f"{number(len(u)).capitalize()} more boards stopped before layout and "
            f"have no PCB to show: {listed}. They are in the boards repository at "
            f"the stage they reached.")


# ---------------------------------------------------------------- LaTeX
UNITS = r"mΩ|Ω|µH|kSa/s|kHz|MHz|Hz|mV|mA|mm|V|A|W"


def tex(s: str) -> str:
    s = s.replace("\\", "\\textbackslash{}")
    s = re.sub(r"([&%$#_{}])", r"\\\1", s)
    s = s.replace("~", "\\textasciitilde{}").replace("^", "\\textasciicircum{}")
    s = re.sub(rf"(\d) ({UNITS})(?![\w/])", r"\1\\,\2", s)
    for a, b in (("\u201c", "``"), ("\u201d", "''"), ("×", "$\\times$"),
                 ("±", "$\\pm$"), ("µ", "$\\mu$"), ("μ", "$\\mu$"),
                 ("Ω", "$\\Omega$"), ("–", "--"), ("—", "---"),
                 ("²", "\\textsuperscript{2}"), ("·", "\\sep")):
        s = s.replace(a, b)
    return s


def tex_plate(p: dict) -> str:
    return (f"\\board{{{p['image']}}}{{{tex(p['name'])}}}%\n"
            f"{{{tex(p['facts'])}}}{{{tex(p['status'])}}}%\n"
            f"{{{wrap(tex(p['caption']))}}}")


def wrap(s: str) -> str:
    return "\n".join(textwrap.wrap(s, 78, break_long_words=False,
                                   break_on_hyphens=False))


def render_tex(m: dict) -> str:
    L = ["% Generated by gallery.py from gallery.yaml and the boards repo.",
         "% Edit those and run sync.py; never edit this file.", "",
         "% " + "=" * 70, "\\section{The boards}",
         f"\\hslead{{{wrap(tex(number(m['count']).capitalize() + ' boards have reached a routed layout. ' + m['lead']))}}}",
         "", "\\begin{hsblock}",
         f"\\hslabel{{Table 1 / the {number(m['count'])} boards and where each one stopped}}\\par\\vspace{{8pt}}",
         "\\footnotesize",
         "\\begin{tabularx}{\\linewidth}{@{}l Y r r >{\\raggedright\\arraybackslash}p{3.3cm}@{}}",
         "\\hstoprule",
         "\\hshead{Board} & \\hshead{What it is} & \\hshead{Layers} & "
         "\\hshead{Size (mm)} & \\hshead{Where it stopped}\\\\", "\\hstoprule"]
    rows = [f"{tex(r['name'])} & {tex(r['what'])} & {r['layers']} & {tex(r['size'])} "
            f"& {tex(r['stage'])}\\\\" for r in m["table"]]
    L += [r + "\\hline" for r in rows[:-1]] + rows[-1:]
    L += ["\\hstoprule", "\\end{tabularx}", "\\end{hsblock}", ""]
    L += [wrap(tex(" ".join(table_note(m)))), ""]
    L += ["\\hsprovenance{" + wrap(
        "Generated by docs/showcase/gallery.py from each board's .kicad\\_pcb "
        "(layers, size, footprints), state.json and fab folder (stage) in the "
        f"boards repository, as last changed on {long_date(m['changed'])}.") + "}",
        "\\newpage", ""]
    for sec in m["sections"]:
        L += ["% " + "-" * 70, f"\\subsection{{{tex(sec['title'])}}}"]
        if sec["label"]:
            L.append(f"\\label{{{sec['label']}}}")
        L.append("")
        for b in sec["blocks"]:
            if b["kind"] == "text":
                L += [wrap(tex(b["text"])), ""]
            elif b["kind"] == "newpage":
                L += ["\\newpage", ""]
            elif b["kind"] == "single":
                h = b.get("height")
                if h:
                    L.append(f"\\setlength{{\\boardh}}{{{h}cm}}")
                L.append(tex_plate(b["plates"][0]))
                if h:
                    L.append("\\setlength{\\boardh}{9cm}")
                L.append("")
            elif b["kind"] == "pair":
                ps = b["plates"] + [None] * (2 - len(b["plates"]))
                L.append("\\boardpair")
                L += [f"{{{tex_plate(p)}}}" if p else "{}" for p in ps]
                L.append("")
        prov = (f"Pictures from docs/showcase/renders, made as that folder's "
                f"README says. Facts from the board files of "
                f"{_and(sec['boards'])} in the boards repository.")
        L += ["\\hsprovenance{" + wrap(tex(prov)) + "}", "\\newpage", ""]
    line = unrouted_line(m)
    if line:
        # Sits under the last section's page break, on a page of its own text.
        L[-2:-1] = []
        L += [wrap(tex(line)), "", "\\newpage", ""]
    return "\n".join(L).rstrip() + "\n"


def _and(names: list[str]) -> str:
    return names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]


# ---------------------------------------------------------------- Markdown
def md_wrap(s: str) -> str:
    return "\n".join(textwrap.wrap(s, 79, break_long_words=False,
                                   break_on_hyphens=False))


def md_caption(p: dict) -> str:
    bits = [f"__{p['name']}__"] + [x for x in (p["facts"], p["status"]) if x]
    return " · ".join(bits) + ". " + p["caption"]


def md_image(p: dict) -> str:
    return f"![{p['name']}](docs/showcase/renders/{picture(p['image']).name})"


def render_md(m: dict) -> str:
    L = ["## The boards", "",
         md_wrap(number(m["count"]).capitalize() + " boards have reached a routed "
                 "layout. " + m["lead"]), "",
         "| Board | What it is | Layers | Size (mm) | Where it stopped |",
         "|---|---|--:|--:|---|"]
    L += [f"| {r['name']} | {r['what']} | {r['layers']} | {r['size']} | {r['stage']} |"
          for r in m["table"]]
    L += ["", md_wrap(" ".join(table_note(m))), ""]
    for sec in m["sections"]:
        L += [f"### {sec['title']}", ""]
        in_table = False
        for b in sec["blocks"]:
            if b["kind"] == "newpage":
                continue
            if b["kind"] != "pair" and in_table:
                L.append("")
                in_table = False
            if b["kind"] == "text":
                L += [md_wrap(b["text"]), ""]
            elif b["kind"] == "single":
                p = b["plates"][0]
                L += [md_image(p), "", md_wrap(f"*{md_caption(p)}*"), ""]
            elif b["kind"] == "pair":
                if not in_table:
                    L += ["| | |", "|---|---|"]
                    in_table = True
                ps = b["plates"]
                L.append("| " + " | ".join(md_image(p) for p in ps)
                         + (" | |" if len(ps) == 1 else " |"))
                L.append("| " + " | ".join(md_caption(p).replace("|", "\\|") for p in ps)
                         + (" | |" if len(ps) == 1 else " |"))
        if in_table:
            L.append("")
    line = unrouted_line(m)
    if line:
        L += [md_wrap(line), ""]
    return "\n".join(L).rstrip() + "\n"


def splice_readme(text: str, body: str) -> str:
    if START not in text or END not in text:
        raise ValueError(f"{README} has no gallery markers")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{body}{END}{tail}"


# ---------------------------------------------------------------- pictures
def picture(image: str) -> Path:
    for ext in (".png", ".jpg"):
        if (RENDERS / f"{image}{ext}").is_file():
            return RENDERS / f"{image}{ext}"
    return RENDERS / f"{image}.png"


def picture_source(b: dict) -> tuple[Path, bool] | None:
    """The board's own render to finish for the page, and whether it is a
    straight-down view (which drops the drop shadow); None when it has none."""
    ws, d, n = b["ws"], b["dir"], b["name"]
    angled = [f"reports/layers/{d}_iso.png", f"render/{d}_iso.png",
              f"renders/{d}_iso.png", f"reports/{d}_iso.png"]
    top = [f"reports/{d}_top.png", f"reports/render_final/{n}_top.png",
           f"reports/{n}_top.png", f"render/{d}_top.png", f"renders/{d}_top.png"]
    for rel in angled:
        if (ws / rel).is_file():
            return ws / rel, False
    for rel in top:
        if (ws / rel).is_file():
            return ws / rel, True
    return None


def make_pictures(root: Path, names: list[str]) -> list[dict]:
    """Make renders/<name>.png for each shown board that has no picture."""
    allb = boards(root)
    made = []
    for n in names:
        if picture(n).is_file() or n not in allb:
            continue
        src = picture_source(allb[n])
        if src:
            cmd = [sys.executable, str(HERE / "_finish.py")]
            cmd += ["--opaque-only"] if src[1] else []
            cmd += [str(src[0]), str(RENDERS / f"{n}.png")]
        else:
            cmd = ["bash", str(HERE / "render_boards.sh"), allb[n]["dir"]]
        r = subprocess.run(cmd, capture_output=True, text=True,
                           env={**os.environ, "HWDE_BOARDS_ROOT": str(root)})
        made.append({"board": n, "from": str(src[0]) if src else "render_boards.sh",
                     "ok": r.returncode == 0 and picture(n).is_file(),
                     "log": (r.stdout + r.stderr).strip()[-400:]})
    return made


# ---------------------------------------------------------------- main
def generate(root: Path, write: bool, pictures: bool = False) -> dict:
    spec = yaml.safe_load(SPEC.read_text(encoding="utf-8"))
    m = model(root, spec)
    made = make_pictures(root, m["shown"]) if pictures else []
    missing = sorted({p["image"] for s in m["sections"] for b in s["blocks"]
                      for p in b.get("plates", []) if not picture(p["image"]).is_file()})
    tex_new = render_tex(m)
    old_readme = README.read_text(encoding="utf-8")
    readme_new = splice_readme(old_readme, render_md(m))
    tex_old = TEX_OUT.read_text(encoding="utf-8") if TEX_OUT.exists() else ""
    res = {"boards_root": str(root), "count": m["count"], "shown": m["shown"],
           "new_section": m["new"], "pictures_made": made, "missing_pictures": missing,
           "tex_changed": tex_new != tex_old, "readme_changed": readme_new != old_readme,
           "added": sorted(set(m["shown"]) - set(shown_in_tex(tex_old)) - {spec.get("hero")})
           if tex_old else []}
    if write:
        if res["tex_changed"]:
            TEX_OUT.write_text(tex_new, encoding="utf-8")
        if res["readme_changed"]:
            README.write_text(readme_new, encoding="utf-8")
    return res


def shown_in_tex(text: str) -> list[str]:
    """Board names pictured in a generated gallery.tex."""
    return re.findall(r"\\board\{[^}]*\}\{([^}]*)\}", text)


def shown_in_readme(text: str) -> list[str]:
    """Board names pictured in a README: the hand-written opening and the
    gallery both caption a board's picture "__name__ · N layers"."""
    return re.findall(r"__([\w.-]+)__ · \d+ layers", text)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--boards-root", type=Path, default=None,
                    help="boards repo (default HWDE_BOARDS_ROOT or ~/dev/boards)")
    ap.add_argument("--pictures", action="store_true",
                    help="first make the picture of any shown board that has none")
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 when either copy would change")
    a = ap.parse_args(argv)
    root = (a.boards_root or env.boards_root()).expanduser()
    if not (root / "register.yaml").is_file():
        print(json.dumps({"error": f"no register.yaml under {root}"}))
        return 2
    try:
        res = generate(root, write=not a.check, pictures=a.pictures and not a.check)
    except (OSError, ValueError, KeyError, yaml.YAMLError) as e:
        print(json.dumps({"error": f"{type(e).__name__}: {e}"}))
        return 2
    print(json.dumps(res, indent=1))
    if a.check:
        return 1 if res["tex_changed"] or res["readme_changed"] else 0
    return 1 if res["missing_pictures"] or any(not p["ok"] for p in res["pictures_made"]) else 0


if __name__ == "__main__":
    sys.exit(main())
