"""place_seed - structured seed placement (S9, SPEC P6 stage 1).

Hard constraints first, then satellite clusters, then block-adjacency
arrangement:

1. Clusters (placelib.build_clusters): decoupling.json associations lock each
   cap to its IC pin as a rigid satellite; constraints.json placement.groups
   declares the other satellite families (crystal + load caps, dividers) until
   S7 emits them; everything else is a singleton. board_only / locked /
   placement.fixed footprints never move (they are obstacles).
2. Satellite slots are computed in the anchor's LOCAL frame (they rotate with
   the anchor): each satellite sits just outside the anchor courtyard, facing
   the pad of its target pin (2-pad parts are rotated so the shared-net pad
   points at the pin), deterministically nudged around the perimeter until
   collision-free.
3. placement.edges pins connector clusters to board edges: distributed along
   the declared edge (or at an explicit pos fraction), rotated so the body
   overhang points off-board (explicit rot wins; symmetric parts keep their
   angle), courtyard flush with the edge.
4. Remaining clusters: connectivity-weighted deterministic spring embedding
   (GND 0.2 / power 0.5 / signal 1.0; no RNG - fixed circle init + fixed
   iteration count), then greedy grid legalization (largest first, spiral
   search) against courtyard overlap, board interior, and keepouts.

Emits an ABSOLUTE op list for place_edit.py; --apply applies it and re-checks
legality on the saved file. constraints.json["placement"] shape (all keys
optional, generated by P2/S13 later):

  {"edges":    [{"ref": "J1", "edge": "left|right|top|bottom",
                 "pos": 0..1?, "rot": deg?}],
   "groups":   [{"name": "xtal", "anchor": "Y1", "members": ["C7","C8"],
                 "template": "crystal"?}],
   "keepouts": [{"rect": [x1,y1,x2,y2]} | {"poly": [[x,y],...]},
                "side": "front|back|both"?, "reason": str?],
   "fixed":    ["REF", ...],
   "corridors": [{"a": "J1", "b": "J2", "width_mm": 5.5, "net": "VBUS"?}],
   "sides":    [{"ref": "J1", "side": "front|back", "reason": str?}]}

groups[].template routes the cluster's satellite slotting through
lib/placetemplates.py (T6 p4: "crystal" = symmetric load caps, GND
outboard, warn-only membership audit); absent -> generic slotting.
corridors is CONSUMED BY PLACE_ANNEAL as a keep-clear cost term (T6 P6A-5);
the seed does not lay parts along it yet (full primitive deferred). sides is
also place_anneal's (U19: a pinned ref is never flipped to the other side);
the seed keeps every part on the side the board already has it on.

Edges are in board-render orientation (top = min y; file coordinates grow
downward). Exit 0 legal seed emitted / 1 seed left violations (unplaceable
cluster or illegal result) / 2 error.
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

from shapely import affinity
from shapely.ops import unary_union

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS / "lib"))
sys.path.insert(0, str(SCRIPTS))

import checklib  # noqa: E402
import placelib  # noqa: E402
from geom import _rot  # noqa: E402
from placelib import Cluster, Footprint, PlaceModel  # noqa: E402

OUTWARD = {"left": (-1.0, 0.0), "right": (1.0, 0.0),
           "top": (0.0, -1.0), "bottom": (0.0, 1.0)}
SAT_GAP = 0.3          # mm clearance satellite <-> anchor courtyard
NUDGE_ANGLES = [0] + [s * a for a in range(15, 181, 15) for s in (1, -1)]
SPRING_ITERS = 250


def _ang(v) -> float:
    return math.degrees(math.atan2(v[1], v[0]))


def _unit(v):
    n = math.hypot(v[0], v[1])
    return (v[0] / n, v[1] / n) if n > 1e-9 else (1.0, 0.0)


def _centered(poly):
    c = poly.centroid
    return affinity.translate(poly, -c.x, -c.y)


# ------------------------------------------------------- satellite slots

def layout_satellites(model: PlaceModel, cluster: Cluster,
                      warnings: list[str]) -> dict[str, tuple]:
    """ref -> ((slot_x, slot_y) anchor-origin local frame, rel_angle_deg)."""
    if cluster.template:
        import placetemplates
        slots = placetemplates.layout(model, cluster, warnings)
        if slots is not None:
            return slots
    anchor = model.footprints[cluster.anchor]
    ext = anchor.extents_local()
    ac = anchor.center_local()
    rc = _circumradius(ext)
    placed = [ext]
    slots: dict[str, tuple] = {}

    def keyed(s):
        p = _pin_local(anchor, s)
        return (0, _ang((p[0] - ac[0], p[1] - ac[1])), s.ref) if p \
            else (1, 0.0, s.ref)

    for i, sat in enumerate(sorted(cluster.satellites, key=keyed)):
        fp = model.footprints[sat.ref]
        sat_rel = _centered(fp.extents_local())
        r_sat = _circumradius(sat_rel)
        pin = _pin_local(anchor, sat)
        if pin is None and sat.target_pin is not None:
            warnings.append(f"{cluster.anchor}.{sat.target_pin[1]} not found "
                            f"for satellite {sat.ref} - perimeter slot used")
        if pin is not None:
            base_dir = _unit((pin[0] - ac[0], pin[1] - ac[1]))
            pivot = pin
        else:
            spread = i * (360.0 / max(1, len(cluster.satellites)))
            base_dir = _unit(_rot(1.0, 0.0, spread))
            pivot = (ac[0] + base_dir[0] * rc, ac[1] + base_dir[1] * rc)

        toward = (-base_dir[0], -base_dir[1])  # sat center -> pin direction
        rel = _facing_rel(anchor, fp, sat, toward)
        poly0 = affinity.rotate(sat_rel, -rel, origin=(0, 0))
        chosen = None
        for off in NUDGE_ANGLES:
            d = _unit(_rot(base_dir[0], base_dir[1], off))
            for push in range(14):
                cand = (pivot[0] + d[0] * (r_sat + SAT_GAP + push * 0.4),
                        pivot[1] + d[1] * (r_sat + SAT_GAP + push * 0.4))
                poly = affinity.translate(poly0, cand[0], cand[1])
                if all(poly.intersection(p).area <= placelib.EPS_AREA
                       for p in placed):
                    chosen = (cand, poly)
                    break
            if chosen:
                break
        if chosen is None:  # give it a far slot; legality will flag overlap
            cand = (pivot[0] + base_dir[0] * (r_sat + 5.0),
                    pivot[1] + base_dir[1] * (r_sat + 5.0))
            chosen = (cand, affinity.translate(poly0, *cand))
            warnings.append(f"satellite {sat.ref} could not be slotted "
                            f"collision-free around {cluster.anchor}")
        slots[sat.ref] = (chosen[0], rel)
        placed.append(chosen[1])
    return slots


def _pin_local(anchor: Footprint, sat) -> tuple[float, float] | None:
    if sat.target_pin is None:
        return None
    _ref, number = sat.target_pin
    pads = [p for p in anchor.pads if p.number == str(number)]
    return pads[0].local if pads else None


def _facing_rel(anchor, fp, sat, toward) -> float:
    """Rel rotation pointing the satellite's shared-net pad along `toward`
    (an anchor-frame unit vector from the satellite center to its pin)."""
    pin_net = None
    if sat.target_pin is not None:
        for p in anchor.pads:
            if p.number == str(sat.target_pin[1]):
                pin_net = p.net
                break
    if pin_net is None or len(fp.pads) != 2:
        return 0.0
    facing = [p for p in fp.pads if p.net == pin_net]
    if not facing:
        return 0.0
    cc = fp.center_local()
    off = (facing[0].local[0] - cc[0], facing[0].local[1] - cc[1])
    if math.hypot(*off) < 1e-6:
        return 0.0
    offu = _unit(off)
    return max((0.0, 90.0, 180.0, 270.0),
               key=lambda r: _dot(_rot(offu[0], offu[1], -r), toward))


def _dot(a, b) -> float:
    return a[0] * b[0] + a[1] * b[1]


def _circumradius(poly) -> float:
    minx, miny, maxx, maxy = poly.bounds
    return math.hypot(maxx - minx, maxy - miny) / 2.0


# ------------------------------------------------------- cluster geometry

def cluster_rel_poly(model: PlaceModel, cluster: Cluster, slots) -> tuple:
    """(polygon about the anchor COURTYARD CENTER at rel angle 0, center_local)."""
    anchor = model.footprints[cluster.anchor]
    parts = [anchor.extents_local()]
    for ref, (slot, rel) in slots.items():
        p = affinity.rotate(_centered(model.footprints[ref].extents_local()),
                            -rel, origin=(0, 0))
        parts.append(affinity.translate(p, slot[0], slot[1]))
    u = unary_union(parts)
    ac = anchor.center_local()
    return affinity.translate(u, -ac[0], -ac[1]), ac


def apply_cluster(model: PlaceModel, cluster: Cluster, slots,
                  center: tuple[float, float], angle: float) -> None:
    anchor = model.footprints[cluster.anchor]
    anchor.place_center(center, angle)
    for ref, (slot, rel) in slots.items():
        fp = model.footprints[ref]
        fp.place_center(anchor.to_abs(slot), (angle + rel) % 360.0)


# ------------------------------------------------------- edge placement

def auto_edge_rot(fp: Footprint, edge: str) -> float:
    pads = fp.pads
    if not pads:
        return fp.angle
    pc = (sum(p.local[0] for p in pads) / len(pads),
          sum(p.local[1] for p in pads) / len(pads))
    ec = fp.center_local()
    m = (ec[0] - pc[0], ec[1] - pc[1])
    if math.hypot(*m) < 0.3:
        return fp.angle  # symmetric part - orientation is not inferable
    theta = _ang(m) - _ang(OUTWARD[edge])
    return (round(theta / 90.0) * 90.0) % 360.0


def place_edge_clusters(model, clusters, slots_of, edge_margin, warnings):
    minx, miny, maxx, maxy = model.outline.bounds
    by_edge: dict[str, list[Cluster]] = {}
    for c in clusters:
        if c.edge:
            by_edge.setdefault(c.edge["edge"], []).append(c)
    for edge, group in sorted(by_edge.items()):
        if edge not in OUTWARD:
            warnings.append(f"unknown edge '{edge}' - clusters left in place")
            continue
        group.sort(key=lambda c: (c.edge.get("pos") is None,
                                  c.edge.get("pos") or 0.0, c.anchor))
        o = OUTWARD[edge]
        along = (0.0, 1.0) if edge in ("left", "right") else (1.0, 0.0)
        lo, hi = (miny, maxy) if edge in ("left", "right") else (minx, maxx)
        exy = {"left": minx, "right": maxx, "top": miny, "bottom": maxy}[edge]
        n = len(group)
        for i, c in enumerate(group):
            ref = c.edge["ref"]
            target_fp = model.footprints[ref]
            rot = c.edge.get("rot")
            angle = float(rot) if rot is not None else auto_edge_rot(
                target_fp, edge)
            rel_poly, _ac = cluster_rel_poly(model, c, slots_of[c.anchor])
            poly = affinity.rotate(rel_poly, -angle, origin=(0, 0))
            bminx, bminy, bmaxx, bmaxy = poly.bounds
            outer = max(_dot((x, y), o) for x, y in
                        [(bminx, bminy), (bminx, bmaxy),
                         (bmaxx, bminy), (bmaxx, bmaxy)])
            half_along = (bmaxy - bminy) / 2 if along[1] else \
                (bmaxx - bminx) / 2
            frac = c.edge.get("pos")
            frac = frac if frac is not None else (i + 0.5) / n
            span_lo = lo + edge_margin + half_along
            span_hi = hi - edge_margin - half_along
            at = span_lo + max(0.0, min(1.0, frac)) * max(0.0,
                                                          span_hi - span_lo)
            edge_pt = (exy, at) if along[1] else (at, exy)
            center = (edge_pt[0] - o[0] * outer, edge_pt[1] - o[1] * outer)
            if c.anchor != ref:
                # edge ref is a satellite: pin the cluster by its anchor anyway
                warnings.append(f"edge ref {ref} is a satellite; edge applied "
                                f"to its cluster anchor {c.anchor}")
            apply_cluster(model, c, slots_of[c.anchor], center, angle)


# ------------------------------------------------------- free arrangement

def net_weights(constraints: dict | None, decoupling: dict | None):
    power = {p.get("net") for p in (constraints or {}).get("power", [])}
    power |= {a.get("rail") for a in (decoupling or {}).get(
        "associations", [])}
    power.discard(None)
    gnd = {"GND"} | {a.get("gnd", "GND") for a in (decoupling or {}).get(
        "associations", [])}

    def weight(net: str) -> float:
        if net in gnd:
            return 0.2
        if net in power:
            return 0.5
        return 1.0
    return weight


def connectivity(model: PlaceModel, clusters: list[Cluster], weight):
    nets_of: dict[str, dict[str, int]] = {}
    for c in clusters:
        acc: dict[str, int] = {}
        for ref in c.refs:
            for p in model.footprints[ref].pads:
                if p.net:
                    acc[p.net] = acc.get(p.net, 0) + 1
        nets_of[c.anchor] = acc
    w: dict[tuple[str, str], float] = {}
    names = sorted(nets_of)
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            shared = nets_of[a].keys() & nets_of[b].keys()
            tw = sum(weight(n) for n in shared)
            if tw > 0:
                w[(a, b)] = tw
    return w


def spring_positions(free: list[str], pinned: dict[str, tuple], w,
                     interior_bounds) -> dict[str, tuple]:
    minx, miny, maxx, maxy = interior_bounds
    cx, cy = (minx + maxx) / 2, (miny + maxy) / 2
    n = len(free)
    if n == 0:
        return {}
    area = max((maxx - minx) * (maxy - miny), 1.0)
    k = math.sqrt(area / max(1, n + len(pinned)))
    pos = {}
    rank = sorted(free, key=lambda f: (-sum(v for (a, b), v in w.items()
                                            if f in (a, b)), f))
    r0 = 0.25 * min(maxx - minx, maxy - miny)
    for i, name in enumerate(rank):
        a = 2 * math.pi * i / n
        pos[name] = (cx + r0 * math.cos(a), cy + r0 * math.sin(a))
    t = 0.15 * min(maxx - minx, maxy - miny)
    for _ in range(SPRING_ITERS):
        disp = {f: [0.0, 0.0] for f in free}
        for i, a in enumerate(free):
            for b in free[i + 1:]:
                dx = pos[a][0] - pos[b][0]
                dy = pos[a][1] - pos[b][1]
                d = math.hypot(dx, dy) or 1e-6
                f = k * k / d / d  # classic F-R repulsion k^2/d, as unit*f
                disp[a][0] += dx * f
                disp[a][1] += dy * f
                disp[b][0] -= dx * f
                disp[b][1] -= dy * f
        everything = {**pos, **pinned}
        for (a, b), wt in w.items():
            if a not in everything or b not in everything:
                continue
            dx = everything[a][0] - everything[b][0]
            dy = everything[a][1] - everything[b][1]
            d = math.hypot(dx, dy) or 1e-6
            f = wt * d * d / k  # classic F-R attraction d^2/k, weighted
            if a in disp:
                disp[a][0] -= dx / d * f
                disp[a][1] -= dy / d * f
            if b in disp:
                disp[b][0] += dx / d * f
                disp[b][1] += dy / d * f
        for f in free:
            dx, dy = disp[f]
            d = math.hypot(dx, dy)
            if d > 1e-9:
                step = min(d, t)
                pos[f] = (min(maxx, max(minx, pos[f][0] + dx / d * step)),
                          min(maxy, max(miny, pos[f][1] + dy / d * step)))
        t = max(0.05, t * 0.97)
    return pos


def legalize(model, free_clusters, slots_of, desired, obstacles, interior,
             forbidden, grid, warnings):
    """Largest-first greedy snap to the nearest legal grid position."""
    order = sorted(free_clusters,
                   key=lambda c: (-cluster_rel_poly(model, c,
                                                    slots_of[c.anchor])[0].area,
                                  c.anchor))
    placed_polys = list(obstacles)
    unplaced = []
    minx, miny, maxx, maxy = interior.bounds
    max_r = int(max(maxx - minx, maxy - miny) / grid) + 1
    for c in order:
        rel, _ac = cluster_rel_poly(model, c, slots_of[c.anchor])
        angle = model.footprints[c.anchor].angle
        poly0 = affinity.rotate(rel, -angle, origin=(0, 0))
        want = desired[c.anchor]
        spot = None
        for r in range(max_r):
            ring = []
            for i in range(-r, r + 1):
                for j in range(-r, r + 1):
                    if max(abs(i), abs(j)) != r:
                        continue
                    cand = (want[0] + i * grid, want[1] + j * grid)
                    ring.append(cand)
            for cand in sorted(ring, key=lambda p: (
                    (p[0] - want[0]) ** 2 + (p[1] - want[1]) ** 2,
                    p[1], p[0])):
                poly = affinity.translate(poly0, cand[0], cand[1])
                if poly.difference(interior).area > placelib.EPS_AREA:
                    continue
                if any(poly.intersection(f).area > placelib.EPS_AREA
                       for f in forbidden):
                    continue
                if any(poly.intersection(p).area > placelib.EPS_AREA
                       for p in placed_polys):
                    continue
                spot = cand
                break
            if spot:
                break
        if spot is None:
            unplaced.append(c.anchor)
            warnings.append(f"cluster {c.anchor} could not be legalized "
                            f"- left at its input position")
            continue
        apply_cluster(model, c, slots_of[c.anchor], spot, angle)
        placed_polys.append(affinity.translate(poly0, spot[0], spot[1]))
    return unplaced


# ------------------------------------------------------- driver

def seed(pcb: Path, constraints: dict, decoupling: dict,
         grid: float, edge_margin: float):
    model = PlaceModel(pcb)
    placement = constraints.get("placement") or {}
    hpwl_before = placelib.hpwl(model)["total_mm"]

    clusters, warnings = placelib.build_clusters(model, decoupling, placement)
    import placetemplates
    placetemplates.audit_groups(model, placement, warnings)
    slots_of = {c.anchor: layout_satellites(model, c, warnings)
                for c in clusters}

    edge_clusters = [c for c in clusters if c.edge]
    free_clusters = [c for c in clusters if not c.edge]
    place_edge_clusters(model, edge_clusters, slots_of, edge_margin, warnings)

    fixed_polys = [f.extents_abs() for f in model.footprints.values()
                   if not f.is_movable
                   or f.ref in set(placement.get("fixed", []))]
    edge_polys = []
    for c in edge_clusters:
        rel, _ = cluster_rel_poly(model, c, slots_of[c.anchor])
        fpa = model.footprints[c.anchor]
        edge_polys.append(affinity.translate(
            affinity.rotate(rel, -fpa.angle, origin=(0, 0)),
            *fpa.center_abs()))

    interior = model.outline.buffer(-edge_margin)
    if interior.is_empty:
        raise checklib.CheckError(
            f"board outline too small for edge margin {edge_margin} mm")
    forbidden = [p for side in ("front", "back")
                 for p, _why in placelib._forbidden(model, placement, side)]
    weight = net_weights(constraints, decoupling)
    w = connectivity(model, clusters, weight)
    pinned = {c.anchor: model.footprints[c.anchor].center_abs()
              for c in edge_clusters}
    desired = spring_positions([c.anchor for c in free_clusters], pinned, w,
                               interior.bounds)
    unplaced = legalize(model, free_clusters, slots_of, desired,
                        fixed_polys + edge_polys, interior, forbidden, grid,
                        warnings)

    ops = []
    for c in clusters:
        for ref in c.refs:
            fp = model.footprints[ref]
            ops.append({"op": "place", "ref": ref,
                        "x": checklib.rnd(fp.pos[0]),
                        "y": checklib.rnd(fp.pos[1]),
                        "deg": checklib.rnd(fp.angle % 360.0),
                        "side": fp.side})
    violations = [checklib.violation(
        "place", "error", model.footprints[a].center_abs(), None, None, [a],
        f"seed could not legalize cluster {a}", placelib.SOURCE,
        kind="seed_unplaced") for a in unplaced]
    facts = {
        "clusters": [{"anchor": c.anchor,
                      "satellites": [s.ref for s in c.satellites],
                      "edge": (c.edge or {}).get("edge")} for c in clusters],
        "warnings": warnings,
        "hpwl_before_mm": hpwl_before,
        "hpwl_seed_mm": placelib.hpwl(model)["total_mm"],
    }
    return ops, violations, facts, model


def run(argv: list[str] | None = None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--pcb", required=True)
    ap.add_argument("--constraints", default=None,
                    help="constraints.json (default: next to the board)")
    ap.add_argument("--decoupling", default=None,
                    help="decoupling.json (default: next to the board)")
    ap.add_argument("--ops-out", required=True)
    ap.add_argument("--apply", action="store_true",
                    help="apply the ops to the board via place_edit")
    ap.add_argument("--grid-mm", type=float, default=1.0)
    ap.add_argument("--edge-margin-mm", type=float, default=0.8)
    ap.add_argument("--out-report", default=None)
    args = ap.parse_args(argv)

    pcb = Path(args.pcb)
    if not pcb.is_file():
        raise checklib.CheckError(f"board not found: {pcb}")

    def sidecar(explicit, name):
        if explicit:
            return checklib.load_json(explicit, name)
        p = pcb.parent / name
        return checklib.load_json(p, name) if p.is_file() else {}

    constraints = sidecar(args.constraints, "constraints.json")
    decoupling = sidecar(args.decoupling, "decoupling.json")

    ops, violations, facts, _model = seed(pcb, constraints, decoupling,
                                          args.grid_mm, args.edge_margin_mm)
    import json
    Path(args.ops_out).write_text(
        json.dumps({"version": 1, "ops": ops}, indent=1), encoding="utf-8")
    facts["ops_out"] = args.ops_out

    if args.apply and ops:
        import place_edit
        place_edit.apply_ops(pcb, ops)
        placement = constraints.get("placement")
        model_after = placelib.PlaceModel(pcb)
        violations = violations + placelib.legality_violations(
            model_after, placement)
        facts["applied"] = True
        facts["hpwl_applied_mm"] = placelib.hpwl(model_after)["total_mm"]

    payload = checklib.report("place_seed", str(pcb), violations, **facts)
    return payload, args.out_report


def main(argv: list[str] | None = None) -> int:
    return checklib.cli_wrap("place_seed", lambda: run(argv))


if __name__ == "__main__":
    sys.exit(main())
